import React, { useState, useEffect } from "react";

const ContentGeneration = () => {
  const [prompt, setPrompt] = useState("");
  const [generationType, setGenerationType] = useState("lesson");
  const [parameters, setParameters] = useState({
    // These would be passed from settings in a real app
    temperature: 0.7,
    maxTokens: 1000,
    model: "gpt-4",
  });
  const [contextChunks, setContextChunks] = useState([]);
  const [generatedContent, setGeneratedContent] = useState("");
  const [loading, setLoading] = useState(false);
  const [generationHistory, setGenerationHistory] = useState([]);

  // Mock context retrieval from vector DB
  useEffect(() => {
    const fetchMockContext = () => {
      if (!prompt.trim()) {
        setContextChunks([]);
        return;
      }

      // Simulate API delay
      setTimeout(() => {
        const mockChunks = [
          {
            content: `This is a mock context chunk related to "${prompt}". In a real application, this would be retrieved from your vector database based on semantic similarity.`,
            source: "knowledge_base.pdf",
            score: 0.89,
          },
          {
            content: `Another relevant context piece about ${prompt}. Vector DBs help find the most semantically similar content to your query.`,
            source: "educational_materials.docx",
            score: 0.76,
          },
          {
            content: `Historical context and background information related to your query: "${prompt}". This helps the AI generate more accurate and relevant content.`,
            source: "textbook_chapter.md",
            score: 0.68,
          },
        ];
        setContextChunks(mockChunks);
      }, 300);
    };

    const debounceTimer = setTimeout(fetchMockContext, 500);
    return () => clearTimeout(debounceTimer);
  }, [prompt]);

  // Mock content generation
  const handleGenerate = async () => {
    if (!prompt.trim()) return;

    setLoading(true);
    setGeneratedContent("");

    try {
      // Simulate API call delay
      await new Promise((resolve) => setTimeout(resolve, 2000));

      const generationJob = {
        prompt,
        type: generationType,
        parameters,
        contextChunks,
        timestamp: new Date().toISOString(),
      };

      // Generate mock content based on type
      let mockOutput = "";

      switch (generationType) {
        case "lesson":
          mockOutput = `# Lesson: ${prompt}\n\n## Introduction\nThis is a comprehensive lesson about "${prompt}". In a real application, this content would be generated by an AI model using the parameters:\n- Temperature: ${parameters.temperature}\n- Max Tokens: ${parameters.maxTokens}\n- Model: ${parameters.model}\n\n## Key Concepts\n1. **Fundamental Principles**: Detailed explanation of core concepts.\n2. **Practical Applications**: Real-world examples and use cases.\n3. **Advanced Topics**: Deeper insights for advanced learners.\n\n## Summary\nThis lesson provides a solid foundation in ${prompt} and prepares you for more advanced study.`;
          break;

        case "quiz":
          mockOutput = `# Quiz: ${prompt}\n\n## Multiple Choice Questions\n\n1. **What is the main concept behind ${prompt}?**\n   A) Option A\n   B) Option B\n   C) Option C\n   D) Option D\n   \n   *Correct Answer: B*\n\n2. **Which of the following best describes ${prompt}?**\n   A) Description A\n   B) Description B\n   C) Description C\n   D) Description D\n   \n   *Correct Answer: A*\n\n## True/False Questions\n\n1. ${prompt} is always true. (False)\n2. The principles of ${prompt} apply universally. (True)\n\n## Short Answer Questions\n\n1. Explain the significance of ${prompt} in modern contexts.`;
          break;

        case "summary":
          mockOutput = `# Summary: ${prompt}\n\n## Key Points\n- **Main Idea**: Core concept of ${prompt}\n- **Important Details**: Critical information and context\n- **Applications**: How ${prompt} is used in practice\n- **Implications**: Broader impact and significance\n\n## Takeaways\n1. First key takeaway about ${prompt}\n2. Second important insight\n3. Third major point to remember\n\n## Conclusion\nThis summary captures the essential elements of ${prompt} for quick reference and review.`;
          break;

        case "image":
          mockOutput =
            "https://via.placeholder.com/600x400/3B82F6/FFFFFF?text=Generated+Image+Placeholder";
          break;

        case "voice":
          mockOutput = "https://www.soundjay.com/button/button-1.mp3";
          break;

        default:
          mockOutput = `Generated content for: "${prompt}"\n\nThis is mock content that simulates what would be generated by the AI system. In a real implementation, this would be actual AI-generated content based on your prompt and parameters.`;
      }

      const result = {
        ...generationJob,
        id: Date.now(),
        output: mockOutput,
        status: "completed",
      };

      setGeneratedContent(mockOutput);
      setGenerationHistory((prev) => [result, ...prev]);

      // In real app: await axios.post("http://localhost:8000/save-generation-job", result);
      console.log("Would save generation job:", result);
    } catch (err) {
      console.error("Generation error:", err);
      setGeneratedContent("Error generating content. Please try again.");
    } finally {
      setLoading(false);
    }
  };

  // Mock save function
  const handleSave = async () => {
    if (!generatedContent) return;

    try {
      // In real app: await axios.post("http://localhost:8000/save-content", { ... })
      console.log("Would save content:", {
        content: generatedContent,
        type: generationType,
      });
      alert("Content saved successfully! (Mock implementation)");
    } catch (err) {
      console.error("Save error:", err);
      alert("Error saving content.");
    }
  };

  // Mock export function
  const handleExport = async (format) => {
    if (!generatedContent) return;

    try {
      // In real app: actual export API call
      console.log(`Would export as ${format}:`, generatedContent);
      alert(`Exported as ${format.toUpperCase()}! (Mock implementation)`);
    } catch (err) {
      console.error(`Export ${format} error:`, err);
      alert(`Error exporting as ${format.toUpperCase()}`);
    }
  };

  const handleRegenerate = () => {
    handleGenerate();
  };

  return (
    <div className="min-h-screen bg-gray-50 p-6">
      <div className="max-w-6xl mx-auto">
        <header className="mb-8">
          <h1 className="text-3xl font-bold text-gray-900 mb-2">
            🚀 AI Content Generation Studio
          </h1>
          <p className="text-gray-600">
            Generate educational content, quizzes, summaries, and multimedia
            using advanced AI models
          </p>
        </header>

        <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
          {/* Left Column - Input & Controls */}
          <div className="lg:col-span-2 space-y-6">
            {/* Prompt Input */}
            <div className="bg-white rounded-lg shadow-sm border p-6">
              <h2 className="text-lg font-semibold mb-3">Content Prompt</h2>
              <textarea
                className="w-full p-4 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent resize-vertical"
                rows="6"
                placeholder="Describe what you want to generate... (e.g., 'Explain quantum physics for beginners', 'Create a quiz about Renaissance art', 'Summarize the key points of machine learning')"
                value={prompt}
                onChange={(e) => setPrompt(e.target.value)}
              />
            </div>

            {/* Generated Output - Large box below prompt */}
            {generatedContent && (
              <div className="bg-white rounded-lg shadow-sm border p-6">
                <div className="flex justify-between items-center mb-4">
                  <h2 className="text-lg font-semibold">
                    ✨ Generated Content
                  </h2>
                  <span className="px-2 py-1 bg-blue-100 text-blue-800 text-xs rounded capitalize">
                    {generationType}
                  </span>
                </div>

                <div className="prose max-w-none">
                  {generationType === "image" ? (
                    <div className="text-center">
                      <img
                        src={generatedContent}
                        alt="Generated content"
                        className="rounded-lg max-w-full mx-auto"
                      />
                      <p className="text-sm text-gray-500 mt-2">
                        Mock image placeholder - real implementation would
                        generate actual images
                      </p>
                    </div>
                  ) : generationType === "voice" ? (
                    <div className="text-center">
                      <audio controls className="w-full max-w-md mx-auto">
                        <source src={generatedContent} type="audio/mpeg" />
                        Your browser does not support the audio element.
                      </audio>
                      <p className="text-sm text-gray-500 mt-2">
                        Mock audio placeholder - real implementation would
                        generate actual voice
                      </p>
                    </div>
                  ) : (
                    <div className="whitespace-pre-wrap text-gray-700 bg-gray-50 p-6 rounded-lg min-h-[400px] max-h-[600px] overflow-y-auto">
                      {generatedContent}
                    </div>
                  )}
                </div>

                {/* Save & Export Bar */}
                <div className="flex flex-wrap gap-2 mt-4 pt-4 border-t">
                  <button
                    onClick={handleSave}
                    className="px-4 py-2 bg-green-600 text-white rounded-lg hover:bg-green-700 transition-colors"
                  >
                    💾 Save
                  </button>
                  <button
                    onClick={() => handleExport("pdf")}
                    className="px-4 py-2 bg-red-600 text-white rounded-lg hover:bg-red-700 transition-colors"
                  >
                    📄 PDF
                  </button>
                  <button
                    onClick={() => handleExport("docx")}
                    className="px-4 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700 transition-colors"
                  >
                    📝 DOCX
                  </button>
                  <button
                    onClick={handleRegenerate}
                    className="px-4 py-2 bg-purple-600 text-white rounded-lg hover:bg-purple-700 transition-colors"
                  >
                    🔄 Regenerate
                  </button>
                </div>
              </div>
            )}

            {/* Generation Controls */}
            <div className="bg-white rounded-lg shadow-sm border p-6">
              <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                {/* Generation Type Selector */}
                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-2">
                    Content Type
                  </label>
                  <select
                    className="w-full p-3 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500"
                    value={generationType}
                    onChange={(e) => setGenerationType(e.target.value)}
                  >
                    <option value="lesson">📚 Lesson</option>
                    <option value="quiz">❓ Quiz</option>
                    <option value="summary">📋 Summary</option>
                    <option value="image">🖼️ Image</option>
                    <option value="voice">🎤 Voice</option>
                  </select>
                </div>

                {/* Current Parameters Display (Read-only) */}
                <div className="space-y-3 p-3 bg-gray-50 rounded-lg">
                  <h3 className="text-sm font-medium text-gray-700">
                    Current Parameters
                  </h3>
                  <div className="grid grid-cols-2 gap-2 text-xs">
                    <div>
                      <span className="text-gray-500">Temperature:</span>
                      <div className="font-medium">
                        {parameters.temperature}
                      </div>
                    </div>
                    <div>
                      <span className="text-gray-500">Max Tokens:</span>
                      <div className="font-medium">{parameters.maxTokens}</div>
                    </div>
                    <div>
                      <span className="text-gray-500">Model:</span>
                      <div className="font-medium">{parameters.model}</div>
                    </div>
                    <div className="col-span-2 text-gray-500 text-xs">
                      * Parameters are set in application settings
                    </div>
                  </div>
                </div>
              </div>
            </div>

            {/* Context Preview */}
            {contextChunks.length > 0 && (
              <div className="bg-white rounded-lg shadow-sm border p-6">
                <h2 className="text-lg font-semibold mb-3">
                  📚 Relevant Context (Mock Data)
                </h2>
                <div className="space-y-3 max-h-60 overflow-y-auto">
                  {contextChunks.map((chunk, index) => (
                    <div
                      key={index}
                      className="p-3 bg-gray-50 rounded-lg border"
                    >
                      <p className="text-sm text-gray-700">{chunk.content}</p>
                      <p className="text-xs text-gray-500 mt-1">
                        Source: {chunk.source} • Score:{" "}
                        {chunk.score?.toFixed(3)}
                      </p>
                    </div>
                  ))}
                </div>
              </div>
            )}
          </div>

          {/* Right Column - Actions & History */}
          <div className="space-y-6">
            {/* Generate Button */}
            <button
              onClick={handleGenerate}
              disabled={loading || !prompt.trim()}
              className={`w-full px-6 py-4 rounded-lg text-white font-semibold text-lg transition-colors ${
                loading || !prompt.trim()
                  ? "bg-gray-400 cursor-not-allowed"
                  : "bg-blue-600 hover:bg-blue-700 active:bg-blue-800"
              }`}
            >
              {loading ? (
                <div className="flex items-center justify-center">
                  <div className="animate-spin rounded-full h-5 w-5 border-b-2 border-white mr-2"></div>
                  Generating...
                </div>
              ) : (
                "🚀 Generate Content"
              )}
            </button>

            {/* Generation History */}
            {generationHistory.length > 0 && (
              <div className="bg-white rounded-lg shadow-sm border p-6">
                <h2 className="text-lg font-semibold mb-3">
                  📖 Recent Generations
                </h2>
                <div className="space-y-2 max-h-60 overflow-y-auto">
                  {generationHistory.slice(0, 5).map((job) => (
                    <div
                      key={job.id}
                      className="p-2 border rounded-lg hover:bg-gray-50 cursor-pointer"
                      onClick={() => {
                        setPrompt(job.prompt);
                        setGenerationType(job.type);
                        setGeneratedContent(job.output);
                      }}
                    >
                      <p className="text-sm font-medium truncate">
                        {job.prompt}
                      </p>
                      <p className="text-xs text-gray-500 capitalize">
                        {job.type} •{" "}
                        {new Date(job.timestamp).toLocaleTimeString()}
                      </p>
                    </div>
                  ))}
                </div>
              </div>
            )}
          </div>
        </div>
      </div>
    </div>
  );
};

export default ContentGeneration;
